# Generated by Django 4.0.4 on 2022-05-04 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('github_link', models.CharField(max_length=128)),
                ('publish_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 4, 1, 2, 10, 53665))),
                ('description', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user_profile.user_profile')),
            ],
        ),
    ]
