# Generated by Django 4.0.4 on 2022-05-05 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 5, 13, 5, 10, 974061)),
        ),
    ]
