# Generated by Django 4.0.4 on 2022-05-06 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 6, 16, 11, 41, 380577)),
        ),
    ]
