# Generated by Django 4.0.4 on 2022-05-06 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 6, 21, 9, 31, 146557)),
        ),
    ]
