# Generated by Django 4.0.4 on 2022-05-07 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_user_id_project_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 7, 17, 12, 25, 513295)),
        ),
    ]
